### PR TITLE
spanish translate

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
I don't know very well how github works, and my english is quite bad. I would like someone to tell me if I did it well. Thanks!

**Comment by oduvan** [comment]
Sorry for the long reply...

The commit is good

**Comment by oduvan** [comment]
You can see the changes here https://js.checkio.org/mission/morse-clock/ and here https://py.checkio.org/mission/morse-clock/

**Comment by ghost** [comment]
Thank you very much!

**Comment by ghost** [comment]
I've found some mistakes. I will correct as soon as possible

**Comment by oduvan** [comment]
Thanks

**Pull request merged**
